from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    DoubleType,
    LongType,
    StringType,
    StructField,
    StructType,
)

hourly_schema = StructType(
    [
        StructField("apparent_temperature", ArrayType(DoubleType(), True), False),
        StructField("cloud_cover", ArrayType(LongType(), True), False),
        StructField("cloud_cover_high", ArrayType(LongType(), True), False),
        StructField("cloud_cover_low", ArrayType(LongType(), True), False),
        StructField("cloud_cover_mid", ArrayType(LongType(), True), False),
        StructField("dew_point_2m", ArrayType(DoubleType(), True), False),
        StructField("et0_fao_evapotranspiration", ArrayType(DoubleType(), True), False),
        StructField("evapotranspiration", ArrayType(DoubleType(), True), False),
        StructField("precipitation", ArrayType(DoubleType(), True), False),
        StructField("precipitation_probability", ArrayType(LongType(), True), False),
        StructField("pressure_msl", ArrayType(DoubleType(), True), False),
        StructField("rain", ArrayType(DoubleType(), True), False),
        StructField("relative_humidity_2m", ArrayType(LongType(), True), False),
        StructField("showers", ArrayType(DoubleType(), True), False),
        StructField("snow_depth", ArrayType(DoubleType(), True), False),
        StructField("snowfall", ArrayType(DoubleType(), True), False),
        StructField("soil_moisture_0_to_1cm", ArrayType(DoubleType(), True), False),
        StructField("soil_moisture_1_to_3cm", ArrayType(DoubleType(), True), False),
        StructField("soil_moisture_3_to_9cm", ArrayType(DoubleType(), True), False),
        StructField("soil_moisture_9_to_27cm", ArrayType(DoubleType(), True), False),
        StructField("soil_moisture_27_to_81cm", ArrayType(DoubleType(), True), False),
        StructField("soil_temperature_0cm", ArrayType(DoubleType(), True), False),
        StructField("soil_temperature_6cm", ArrayType(DoubleType(), True), False),
        StructField("soil_temperature_18cm", ArrayType(DoubleType(), True), False),
        StructField("soil_temperature_54cm", ArrayType(DoubleType(), True), False),
        StructField("surface_pressure", ArrayType(DoubleType(), True), False),
        StructField("temperature_2m", ArrayType(DoubleType(), True), False),
        StructField("temperature_80m", ArrayType(DoubleType(), True), False),
        StructField("temperature_120m", ArrayType(DoubleType(), True), False),
        StructField("temperature_180m", ArrayType(DoubleType(), True), False),
        StructField("time", ArrayType(StringType(), True), False),
        StructField("vapour_pressure_deficit", ArrayType(DoubleType(), True), False),
        StructField("visibility", ArrayType(DoubleType(), True), False),
        StructField("weather_code", ArrayType(LongType(), True), False),
        StructField("wind_direction_10m", ArrayType(LongType(), True), False),
        StructField("wind_direction_80m", ArrayType(LongType(), True), False),
        StructField("wind_direction_120m", ArrayType(LongType(), True), False),
        StructField("wind_direction_180m", ArrayType(LongType(), True), False),
        StructField("wind_gusts_10m", ArrayType(DoubleType(), True), False),
        StructField("wind_speed_10m", ArrayType(DoubleType(), True), False),
        StructField("wind_speed_80m", ArrayType(DoubleType(), True), False),
        StructField("wind_speed_120m", ArrayType(DoubleType(), True), False),
        StructField("wind_speed_180m", ArrayType(DoubleType(), True), False),
    ]
)

hourly_units_schema = StructType(
    [
        StructField("apparent_temperature", ArrayType(BinaryType(), True), False),
        StructField("cloud_cover", ArrayType(StringType(), True), False),
        StructField("cloud_cover_high", ArrayType(StringType(), True), False),
        StructField("cloud_cover_low", ArrayType(StringType(), True), False),
        StructField("cloud_cover_mid", ArrayType(StringType(), True), False),
        StructField("dew_point_2m", ArrayType(StringType(), True), False),
        StructField("et0_fao_evapotranspiration", ArrayType(StringType(), True), False),
        StructField("evapotranspiration", ArrayType(StringType(), True), False),
        StructField("precipitation", ArrayType(StringType(), True), False),
        StructField("precipitation_probability", ArrayType(StringType(), True), False),
        StructField("pressure_msl", ArrayType(StringType(), True), False),
        StructField("rain", ArrayType(StringType(), True), False),
        StructField("relative_humidity_2m", ArrayType(StringType(), True), False),
        StructField("showers", ArrayType(StringType(), True), False),
        StructField("snow_depth", ArrayType(StringType(), True), False),
        StructField("snowfall", ArrayType(StringType(), True), False),
        StructField("soil_moisture_0_to_1cm", ArrayType(StringType(), True), False),
        StructField("soil_moisture_1_to_3cm", ArrayType(StringType(), True), False),
        StructField("soil_moisture_3_to_9cm", ArrayType(StringType(), True), False),
        StructField("soil_moisture_9_to_27cm", ArrayType(StringType(), True), False),
        StructField("soil_moisture_27_to_81cm", ArrayType(StringType(), True), False),
        StructField("soil_temperature_0cm", ArrayType(StringType(), True), False),
        StructField("soil_temperature_6cm", ArrayType(StringType(), True), False),
        StructField("soil_temperature_18cm", ArrayType(StringType(), True), False),
        StructField("soil_temperature_54cm", ArrayType(StringType(), True), False),
        StructField("surface_pressure", ArrayType(StringType(), True), False),
        StructField("temperature_2m", ArrayType(StringType(), True), False),
        StructField("temperature_80m", ArrayType(StringType(), True), False),
        StructField("temperature_120m", ArrayType(StringType(), True), False),
        StructField("temperature_180m", ArrayType(StringType(), True), False),
        StructField("time", ArrayType(StringType(), True), False),
        StructField("vapour_pressure_deficit", ArrayType(StringType(), True), False),
        StructField("visibility", ArrayType(StringType(), True), False),
        StructField("weather_code", ArrayType(StringType(), True), False),
        StructField("wind_direction_10m", ArrayType(StringType(), True), False),
        StructField("wind_direction_80m", ArrayType(StringType(), True), False),
        StructField("wind_direction_120m", ArrayType(StringType(), True), False),
        StructField("wind_direction_180m", ArrayType(StringType(), True), False),
        StructField("wind_gusts_10m", ArrayType(StringType(), True), False),
        StructField("wind_speed_10m", ArrayType(StringType(), True), False),
        StructField("wind_speed_80m", ArrayType(StringType(), True), False),
        StructField("wind_speed_120m", ArrayType(StringType(), True), False),
        StructField("wind_speed_180m", ArrayType(StringType(), True), False),
    ]
)

main_schema = StructType(
    [
        StructField("city", StringType(), True),
        StructField("elevation", DoubleType(), True),
        StructField("generationtime_ms", DoubleType(), True),
        StructField("hourly", hourly_schema, True),
        StructField("hourly_units", hourly_units_schema, True),
        StructField("latitude", DoubleType(), True),
        StructField("longitude", DoubleType(), True),
        StructField("timezone", StringType(), True),
        StructField("timezone_abbreviation", StringType(), True),
        StructField("utc_offset_seconds", LongType(), True),
    ]
)
